### ISSUE TITLE
Export functions

### ISSUE THREAD

**Issue by azam** [Grabacr07/KanColleViewer#111]
Data geeks might want to these nice-to-have features implemented.

* Export of current kanmusu details
* Export of data for each attacks

Any open formats (CSV/JSON/Sqlite file) should do fine.

With these, a 3rd party tool may statistically analyze the growth of each kanmusu and probably get some exciting data out of it.

**Comment by Grabacr07** [comment]
There are no plans to be supported by this product.
Please look for or create plugins.
