### ISSUE TITLE
KanColleViewer.exe起動した瞬間はプロキシ経由しない？

### ISSUE THREAD

**Issue by pokemonleo** [Grabacr07/KanColleViewer#114]
通信設定で「通信にプロキシ サーバーを使用する」をチェックし設定していても
KanColleViewer.exe起動してすぐにその設定通りのプロキシサーバーを通してないまま接続してるように見えます

起動後、別のところから艦これページのアドレスをコピーペーストしてればちゃんと通します

**Comment by Grabacr07** [comment]
プロキシ ライブラリが変更されていためクローズします
