### ISSUE TITLE
出撃コンディション設定についての要望（提案）

### ISSUE THREAD

**Issue by Butter-Knife** [Grabacr07/KanColleViewer#120]
動作設定タブの出撃コンディション値入力欄についてです。
状況によって毎回入力しているのですが、結局40か49しかほとんど使いませんので、ラジオボタンで選択するようにしてはどうでしょうか。
コードは分からないので、フォトショで編集したイメージを添付しておきます。
任意入力の欄は疲労状態でも連続出撃したい人向けなどにどうでしょう。

![kcv_teian](https://cloud.githubusercontent.com/assets/8330494/5369802/a29d192a-805c-11e4-8373-2e0de00e524b.png)

**Comment by Grabacr07** [comment]
申し訳ありませんが実装工数に見合ったメリットが感じられないためクローズします
