### ISSUE TITLE
改修工廠で消費した装備数が反映されない

### ISSUE THREAD

**Issue by Butter-Knife** [Grabacr07/KanColleViewer#121]
改修工廠で消費した装備の数が、Kancolleviewerの所持装備数表示に反映されていないようです。

例：
・所持装備900個の状態で、酸素魚雷をLv8からMAXに改修するために未改修魚雷を2個消費
・戦績画面では消費した魚雷の数が反映されて所有装備数は898個
・KanColleViewerでの表示は900個のまま

この表示のズレは母港に戻ってもそのままで、ブラウザ操作でリロードしないと正しい所持数になりませんでした。
また、上記のズレが起きている状態で装備の廃棄をした場合、ズレが残ったまま所持数表示に反映されるようです（これはまだ再検証していないので違ってるかも）
以上、簡単ですが報告でした。

P.S. 先日やっとデイリー・ウィークリー・マンスリーの全任務を達成できまして、発生任務無し画面から母港へ戻るとフリーズする現象が直っているのを確認できました。

**Comment by Grabacr07** [comment]
version 3.6 で修正しました (たぶん)

また、発生任務無しの動作確認ありがとうございました。

**Comment by Butter-Knife** [comment]
更新お疲れ様です。
ネジ１個しかなかったので装備１個消費の改修しかできてませんが、正常に装備個数に反映されました。
イベントが終わったら２個以上の装備を消費するケースもチェックしてみます。

**Comment by Butter-Knife** [comment]
イベクリアしたので試してみました。2個以上の装備消費でも正常に反映されてるようです。
取り急ぎご報告まで。
