### ISSUE TITLE
developのソート機能について

### ISSUE THREAD

**Issue by hexgon** [Grabacr07/KanColleViewer#129]
developで実装されている新しい艦娘一覧のソート機能ですが、これにゲーム内の並びを追加していただけませんでしょうか？もしくは艦種で並び替えた際にはゲーム内と同様の順番で並ぶと使いやすいかと思います。

**Comment by Grabacr07** [comment]
ゲーム内での艦娘の並び順を取得する方法があれば教えてください。

**Comment by hexgon** [comment]
すいません、ゲーム内の並びというのがわかりにくい表現でした。
現在のリリース版の艦娘一覧を艦種でソートした時の順番を意図していました。
（駆逐艦であれば、夕立改二、時雨改二、・・・という順番で並ぶもの）
今のdevelopはID（＝入手順）で並ぶようなので、リリース版のような順番にできないかと思い提案させていただきました。

**Comment by Grabacr07** [comment]
リリース版は、艦種 -> 艦名 (api_sortno) の順でソートする実装です。
現在の開発版では、
![ss150226113149](https://cloud.githubusercontent.com/assets/1779073/6385315/7c36fd3c-bdab-11e4-8a7d-36f4348606e3.png)
で同じことができるはずです。

並べ替え設定で [艦種] を選択したら、その次の項目に自動的に [艦名] をセットした方が便利だ、という話であれば、もう少し他のユーザーの声も訊いてみたいところですね。

(それ以前に api_sortno を「艦名」としているところにも問題がある気がしますが、もっといい名前が思いつかない)

**Comment by hexgon** [comment]
教えていただいた手順で意図通り並べることができました。ありがとうございます。（艦名とは想定外でした）
個人的にはshipsortブランチで実装されたような動作が使いやすいと思いますが、実装に関してはほかのユーザーさんの意見等も含めて検討いただければと思います。
