### ISSUE TITLE
Ask about "add-sortie-log" branch

### ISSUE THREAD

**Issue by xupefei** [Grabacr07/KanColleViewer#135]
Hello,

I saw in the "add-sortie-log" branch you are planing logging of many things, but this branch is not updated  for some time. So could you tell me whether you are still work on this part? If not, I think I can continue develop this branch.

Thanks :)

**UPDATE**: After I checked the source code of `master` and `develop` branch, I think it is better to continue work on `Logger` class in one of those two branches :)

**Comment by smdhz** [comment]
You can just fork it.
