### ISSUE TITLE
最大保有可能装備アイテム数が一致しない

### ISSUE THREAD

**Issue by minet0083** [Grabacr07/KanColleViewer#137]
Ver3.6.1を利用しています。
現在母港を210隻まで拡張している状態で、司令部情報で表示される最大保有装備アイテム数は940となっていますが、KanColleViewer側では937と表示されています。
![snapcrab_noname_2015-3-28_0-28-10_no-00](https://cloud.githubusercontent.com/assets/7688545/6870820/cf60f844-d4e1-11e4-9394-8ee1332110f9.png)

**Comment by Grabacr07** [comment]
艦娘または装備のいずれか (または両方) がその数値以上になると、新たに建造できない＆海域ドロップしないという数値であり、仕様です。(艦これのサーバーからは実際に 937 という数値が来ている)

**Comment by minet0083** [comment]
なるほどそういった仕様があったのですね。自分の知識不足でした。
ありがとうございました。
