### ISSUE TITLE
Binding to 0.0.0.0 allows proxy request from remote machine

### ISSUE THREAD

**Issue by renyidong** [Grabacr07/KanColleViewer#139]
In `Grabacr07.KanColleWrapper/KanColleProxy.cs`
`public void Startup(int proxy = 37564)` calls `FiddlerApplication.Startup(proxy, false, true);` to listen to the proxy port. This allows remote client to connect and make request.
If firewall on user machine is not properly configured, a malicious attacker can use this vulnerability to proxy any requests.

Suggest: Use `FiddlerApplication.Startup(proxy, false, true, false);` (four parameters) or use `Startup(Int32, FiddlerCoreStartupFlags)` instead

Was it a bug or a feature? 
I didn't see any benefit on allowing remote connections, because KanColleViewer is supposed to intercept game requests for one user only.

Cite (from a chinese blog):
https://hjc.im/jing-ti-kancolleviewerda-kai-de-gong-wang-ipduan-kou-chan-sheng-de-an-quan-wen-ti/

**Comment by renyidong** [comment]
Was it a bug or a feature? 
I didn't see any benefit on allowing remote connections, because KanColleViewer is supposed to intercept game requests for one user only.

**Comment by renyidong** [comment]
Cite (from a chinese blog):
https://hjc.im/jing-ti-kancolleviewerda-kai-de-gong-wang-ipduan-kou-chan-sheng-de-an-quan-wen-ti/

**Comment by leeyc0** [comment]
In simple words, running KCV would effectively turns your computer into a open proxy if your computer is directly connecting to the internet or the broadband router is configured into DMZ mode (i.e. one-to-one IP mapping, effectively exposing your computer in the internet).

**Comment by renyidong** [comment]
The issue seems fixed in upstream. Could anyone test and close the issue?

**Comment by leeyc0** [comment]
just a remark, this ticket is a duplicate of #138, can be closed.
