### ISSUE TITLE
内蔵ブラウザのキャッシュをカスタマイズ(Customize cache and profile of the embedded browser)

### ISSUE THREAD

**Issue by misaki-nyanya** [Grabacr07/KanColleViewer#142]
Sorry I don't know anything about C#, but if it is possible to customize cache and profile of the embedded browser?
内蔵ブラウザのキャッシュをカスタマイズ　可能性がありますか？

for example, if I want to place them under the same folder of KCV

**Comment by linnaea** [comment]
Not possible with WPF WebBrowser control, the documentation for the control is here: https://msdn.microsoft.com/en-us/library/system.windows.controls.webbrowser(v=vs.110).aspx

I have personally experimented with hosting Chromium as the browser, which would permit this, but that would create a hell lot of issues and it's definitely not worth the hassle.

Someone should close this issue as WONTFIX or INVALID.

**Comment by Grabacr07** [comment]
Sorry, there are no plans to be supported by this product.
