### ISSUE TITLE
統合タブと艦隊タブで退避状態が表示されない

### ISSUE THREAD

**Issue by veigr** [Grabacr07/KanColleViewer#143]
#### 再現手順

0. 第一艦隊旗艦に艦隊司令部施設を装備した連合艦隊で出撃
0. 誰かを大破させる
0. 進撃時に護衛退避を実行する

#### 期待結果

入渠中と同様に退避状態が表示される

#### 実際の結果

退避状態が表示されず、退避した艦の判別ができない

#### 備考

* 艦隊詳細画面では表示される
* `HasFlagConverter` の使い方が間違っている気がする

**Comment by Grabacr07** [comment]
@fe483f1b887d2cfdefb1acbb1c41d5ebf7ba649c

**Comment by veigr** [comment]
連合艦隊関連は多分コミケ終わるまで確認するヒマがないので誰か。。。

**Comment by nizuru** [comment]
お疲れ様です。
いつもお世話になっております。

さきほど2015夏イベE7丙を攻略中に再現手順を実施しましたので結果を報告いたします。

・結論
退避状態が表示されないままとなっておりました。

・実施手順
1.第一艦隊旗艦に艦隊司令部施設を装備した連合艦隊で出撃
2.Eマスにて第二艦隊に大破艦が発生
3.退避を実行
4.そのまま進軍

・状態
※空母機動部隊で編成しております。
第一艦隊は6隻
第二艦隊は4隻+(退避艦2隻)

・結果
総合タブの第二艦隊の艦隊情報には「大破した艦娘がいます！！！」と表示される
艦隊タブの第二艦隊の艦隊情報には同じく「大破した艦娘がいます！！！」と表示される
艦隊タブ→艦隊詳細ボタン押下→艦隊詳細画面表示を実施しても「大破(轟沈の可能性あり)」と表示される

・環境
KanColleViewer ver4.1.2
Windows7 64bit Home
flash(activeX)13.0.0.232
IE11

・備考
4.1.2のソースファイルをダウンロード後、winmergeにて該当箇所の修正が含まれていることを確認済み
(お門違いの確認でしたらすみません。)

以上です。
よろしくお願いいたします。

**Comment by nizuru** [comment]
総合タブと艦隊タブは画像を取り忘れてしまいました。すみません。
艦隊詳細画面のみ残っていたので念のため添付いたします。
画像で雪風大破となっており秋月が健在ですが進軍している状態でこの表示となっておりました。
ボスマスまでいって帰還しましたが、道中この表示のままとなっておりました。

![default](https://cloud.githubusercontent.com/assets/13846161/9511846/d89aacc4-4cb5-11e5-8bec-47f3a930c97f.png)

**Comment by Grabacr07** [comment]
4.1.3 で修正しました。
https://github.com/Grabacr07/KanColleViewer/commit/8ce465bba62c3cd73d5baf66c982139b50876596
