### ISSUE TITLE
「ツール」タブのプラグインリストが縦スクロールできない

### ISSUE THREAD

**Issue by veigr** [Grabacr07/KanColleViewer#148]
#### 再現手順

0. 起動
0. ツールタブを開く
0. プラグインリストが見切れるまで縦幅を縮小する

#### 期待結果

縦スクロールバーが表示され、スクロールできるようになる

#### 実際の結果

縦スクロールバーが表示されず、スクロールできない

#### 備考

* Grabacr07.KanColleViewer.Views.Contents.Tools.xaml の当該 ListBox の Template が StackPanel になっている
* ScrollViewerにするとスクロールできるようになる

**Comment by smdhz** [comment]
いそそのScrollViewerを消してください
使いたい人は自分から追加し、そうしないと使いたくない人にはBinding ActualHeightとか、面倒です。

**Comment by veigr** [comment]
それは恐らく、 ToolView が挿入される ContentControl の親になっている ScrollViewer (Grid.Column="1") の話ですよね？
その意見には同意しますが、この issue はその話ではなく、左隣の ListBox (Grid.Column="0, ItemsSource="{Binding Tools}") の話です。

https://github.com/Grabacr07/KanColleViewer/blob/master/Grabacr07.KanColleViewer/Views/Contents/Tools.xaml#L25-L35

**Comment by smdhz** [comment]
なるほど、勉強になりました

**Comment by veigr** [comment]
いつの間にか直ってた
