### ISSUE TITLE
3.8.2 cannot launch?

### ISSUE THREAD

**Issue by Diablohu** [Grabacr07/KanColleViewer#149]
error log for me, in simplified chinese

the problem maybe FiddlerCore4 expected 4.4.8.4, but bundled 4.4.9.8 in release package?

**EDIT: problem solved. some plugins expect FiddlerCore4 4.4.8.4. so I deleted them...**

===========================================================
ERROR, date = 2015/5/25 18:52:35 +08:00, sender = System.Windows.Threading.Dispatcher,
System.IO.FileNotFoundException: 未能加载文件或程序集“FiddlerCore4, Version=4.4.8.4, Culture=neutral, PublicKeyToken=67cb91587178ac5a”或它的某一个依赖项。系统找不到指定的文件。
文件名:“FiddlerCore4, Version=4.4.8.4, Culture=neutral, PublicKeyToken=67cb91587178ac5a”
   在 d_f_32.KanColleCacher.FiddlerRules._AppendToFiddler()
   在 d_f_32.KanColleCacher.KanColleCacher.Initialize()
   在 d_f_32.KanColleCacher.KanColleCacher_Initializer.Initialize()
   在 Grabacr07.KanColleViewer.Composition.AggregateNotifier.<Initialize>b__2(INotifier x)
   在 System.Linq.EnumerableEx.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   在 Grabacr07.KanColleViewer.Composition.AggregateNotifier.Initialize()
   在 Grabacr07.KanColleViewer.Composition.PluginHost.Initialize()
   在 Grabacr07.KanColleViewer.App.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

警告: 程序集绑定日志记录被关闭。
要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)设置为 1。
注意: 会有一些与程序集绑定失败日志记录关联的性能损失。
要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。

===========================================================
ERROR, date = 2015/5/25 18:52:35 +08:00, sender = 名称:KanColleViewer.exe
无上下文策略。
,
System.IO.FileNotFoundException: 未能加载文件或程序集“FiddlerCore4, Version=4.4.8.4, Culture=neutral, PublicKeyToken=67cb91587178ac5a”或它的某一个依赖项。系统找不到指定的文件。
文件名:“FiddlerCore4, Version=4.4.8.4, Culture=neutral, PublicKeyToken=67cb91587178ac5a”
   在 d_f_32.KanColleCacher.FiddlerRules._AppendToFiddler()
   在 d_f_32.KanColleCacher.KanColleCacher.Initialize()
   在 d_f_32.KanColleCacher.KanColleCacher_Initializer.Initialize()
   在 Grabacr07.KanColleViewer.Composition.AggregateNotifier.<Initialize>b__2(INotifier x)
   在 System.Linq.EnumerableEx.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   在 Grabacr07.KanColleViewer.Composition.AggregateNotifier.Initialize()
   在 Grabacr07.KanColleViewer.Composition.PluginHost.Initialize()
   在 Grabacr07.KanColleViewer.App.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   在 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   在 System.Windows.Threading.Dispatcher.Run()
   在 System.Windows.Application.RunDispatcher(Object ignore)
   在 System.Windows.Application.RunInternal(Window window)
   在 System.Windows.Application.Run(Window window)
   在 Grabacr07.KanColleViewer.App.Main()

警告: 程序集绑定日志记录被关闭。
要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)设置为 1。
注意: 会有一些与程序集绑定失败日志记录关联的性能损失。
要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。

**Comment by Butter-Knife** [comment]
Same thing happened on my PC too.
たぶん同じ内容だと思いますけどエラーログ貼っておきます。

===========================================================
ERROR, date = 15/05/25 21:11:40 +09:00, sender = 名前:KanColleViewer.exe
コンテキスト ポリシーがありません。
,
System.ComponentModel.Composition.CompositionException: コンポジションで、コンポジション エラーが 1 件発生しました。根本原因は次のとおりです。 詳細については、CompositionException.Errors プロパティを確認してください。

1) ファイルまたはアセンブリ 'FiddlerCore4, Version=4.4.8.4, Culture=neutral, PublicKeyToken=67cb91587178ac5a'、またはその依存関係の 1 つが読み込めませんでした。指定されたファイルが見つかりません。

結果: 'EventMapHpViewer.MapHpViewer' 型のインスタンスの作成中に例外が発生しました。

結果: パーツ 'EventMapHpViewer.MapHpViewer' をアクティブにできません。
要素: EventMapHpViewer.MapHpViewer -->  EventMapHpViewer.MapHpViewer -->  DirectoryCatalog (Path="C:\Game\kancolle tools\KanColleViewer\Plugins")

結果: パーツ 'EventMapHpViewer.MapHpViewer' のエクスポート 'EventMapHpViewer.MapHpViewer (ContractName="Grabacr07.KanColleViewer.Composition.IToolPlugin")' を取得できません。
要素: EventMapHpViewer.MapHpViewer (ContractName="Grabacr07.KanColleViewer.Composition.IToolPlugin") -->  EventMapHpViewer.MapHpViewer -->  DirectoryCatalog (Path="C:\Game\kancolle tools\KanColleViewer\Plugins")

   場所 System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)
   場所 System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)
   場所 System.ComponentModel.Composition.Hosting.CatalogExportProvider.CatalogExport.GetExportedValueCore()
   場所 System.ComponentModel.Composition.Primitives.Export.get_Value()
   場所 System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
   場所 System.ComponentModel.Composition.ExportServices.<>c__DisplayClass4`2.<CreateStronglyTypedLazyOfTM>b__1()
   場所 System.Lazy`1.CreateValue()
   場所 System.Lazy`1.LazyInitValue()
   場所 System.Lazy`1.get_Value()
   場所 Grabacr07.KanColleViewer.ViewModels.Composition.PluginViewModelBase`1..ctor(Lazy`2 plugin)
   場所 Grabacr07.KanColleViewer.ViewModels.SettingsViewModel.<ReloadPlugins>b__18(Lazy`2 x)
   場所 System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   場所 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   場所 Grabacr07.KanColleViewer.ViewModels.SettingsViewModel.ReloadPlugins()
   場所 Grabacr07.KanColleViewer.ViewModels.SettingsViewModel..ctor()
   場所 Grabacr07.KanColleViewer.ViewModels.MainWindowViewModel..ctor()
   場所 Grabacr07.KanColleViewer.App.OnStartup(StartupEventArgs e)
   場所 System.Windows.Application.<.ctor>b__1(Object unused)
   場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   場所 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   場所 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   場所 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   場所 System.Windows.Threading.DispatcherOperation.Invoke()
   場所 System.Windows.Threading.Dispatcher.ProcessQueue()
   場所 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   場所 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   場所 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   場所 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   場所 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   場所 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   場所 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   場所 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   場所 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   場所 System.Windows.Threading.Dispatcher.Run()
   場所 System.Windows.Application.RunDispatcher(Object ignore)
   場所 System.Windows.Application.RunInternal(Window window)
   場所 System.Windows.Application.Run(Window window)
   場所 Grabacr07.KanColleViewer.App.Main()

**Comment by Grabacr07** [comment]
Cause is that EventMapHpViewer plugin is old.
Please replace the new version.

仰る通り、EventMapHpViewer が古いのが原因です。
この中にある最新バージョンで置き換えれば解決すると思われます。
https://github.com/Grabacr07/KanColleViewer/releases/download/v3.8.2/KanColleViewer.ver.3.8.2.zip

**Comment by smdhz** [comment]
Pull requestはすでに出しだので、ご覧ください
https://github.com/Grabacr07/EventMapHpViewer/pull/1

**Comment by Butter-Knife** [comment]
DLLを置き換えたところ、ちゃんと起動するようになりました。
上記エラーが発生した時はファイルを全て上書きしたのでちょっと不思議でしたが、今確認したらリリース直後のzipにはEventMapHpViewerが含まれてなかったようです（・ω・ゞ。
ともあれ対応ありがとうございました（・ω・ゞ
