### ISSUE TITLE
KCV 3.8.2rev1 crashes frequently under Windows 10 Pro (64bit)

### ISSUE THREAD

**Issue by calculushk** [Grabacr07/KanColleViewer#155]
Debug using Visual Studio 2013 when KCV crashes.

System.AccessViolationException was unhandled
Message: An unhandled exception of type 'System.AccessViolationException' occurred in WindowsBase.dll
Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

P.S. I have no problem using KCV under Windows 8.1 before the upgrade
P.S.2 Any possibility related to .NET 4.6 's bug about RyuJIT? http://blogs.msdn.com/b/dotnet/archive/2015/07/28/ryujit-bug-advisory-in-the-net-framework-4-6.aspx
P.S.3 I can read Japanese, feel free to use Japanese if you are more comfortable =D

**Comment by TOCK-Chiu** [comment]
Maybe you can follow the instruction to disable tail call optimization in the RyuJIT, seeing if the issue is still there?

**Comment by Grabacr07** [comment]
Does this issue occur in Visual Studio 2015 RTM version?

少なくとも私の手元のどの環境でも発生しないので、対応が難しいです。

**Comment by calculushk** [comment]
I cannot repeat the issue again. The bug disappears the other day. I don't know if the problem is patched by the Windows Updates or this is caused by other reasons. I will keep seeing if the problem still exists.
