### ISSUE TITLE
Can't set the WS_EX_LAYERED bit to 1.

### ISSUE THREAD

**Issue by lanhao34** [Grabacr07/KanColleViewer#156]
Thank you for developing the KCV. I'm tring to use setWindowLong function to set the WS_EX_LAYERED bit of KCV to 1, but I failed. I have searched on the Internet, but I still can't solve it. Can you help me with this?

**Comment by Grabacr07** [comment]
If you seek the support, you should at least present the code.
And please discussed elsewhere if you want talk about remodeling.
