### ISSUE TITLE
装備一覧ボタンを押下した際にKanColleViewerが落ちる

### ISSUE THREAD

**Issue by nizuru** [Grabacr07/KanColleViewer#161]
バグ報告がどこで行えばよいかわからずGitHubに登録してからの報告と判断してこの場で報告いたします。

・概要
装備一覧ボタンを押下した際にKanColleViewerプロセスが落ちる。タスクマネージャ上からも消えている。

・経緯
1-5に以下の編成で出撃を行いました。
軽空母
航戦
軽巡
駆逐

このとき熟練度を上げようと考え軽空母に熟練度が2の99艦爆(江草)を3つ　熟練度0の彩雲を1つのせました。

そして1-5のボスマスの戦闘終了後母港にもどってきたところ
改装画面上では江草の熟練度が3になったものが1つ熟練度が2にままのものが2つ　彩雲は熟練度が1になっていました。
しかしながら艦隊タブ上ではポップアップした情報が1-5出撃前のもの(熟練度が2の99艦爆(江草)が3つ　熟練度0の彩雲が1つ)
となっておりこれは変だなということで総合タブから装備一覧画面で熟練度を再度確認しようと思い「装備一覧」ボタンを押下したところ
概要のとおりKanColleViewerプロセスが落ちました。
もういちど出撃したところ再現性がありました。

・再現手順
1.艦載機をのせて出撃
2.母港帰還後に熟練度が変化している場合装備一覧画面押下で落ちる

・期待結果
KanColleViewerプロセスが落ちないこと

・実際の結果
KanColleViewerプロセスが落ちる

・再現性
あり

--
環境

KanColleViewer ver4.1.0
Windows7 64bit Home
flash(activeX)13.0.0.232
IE11

--
備考
他に必要な情報などあれば追加いたします。
どうぞよろしくお願いいたします。

**Comment by nizuru** [comment]
申し訳ありません。
落ちた際のエラーログをテンプします。

--
===========================================================
ERROR, date = 2015/08/18 15:13:05 +09:00, sender = System.Windows.Threading.Dispatcher,
System.Collections.Generic.KeyNotFoundException: 指定されたキーはディレクトリ内に存在しませんでした。
   場所 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   場所 Grabacr07.KanColleViewer.ViewModels.Catalogs.SlotItemCounter.AddShip(Ship ship, Int32 itemLevel, Int32 adept)
   場所 Grabacr07.KanColleViewer.ViewModels.Catalogs.SlotItemCatalogViewModel.UpdateCore()
   場所 Grabacr07.KanColleViewer.ViewModels.Catalogs.SlotItemCatalogViewModel.<>c.<.ctor>b__12_1(Unit _)
   場所 System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   場所 System.Reactive.Stubs.<.cctor>b__1(Exception ex)
   場所 System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   場所 System.Reactive.Concurrency.ObserveOn`1.ObserveOnSink.OnErrorPosted(Object error)
   場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Grabacr07** [comment]
詳細な情報ありがとうございます。
ひとまず頂いた情報をもとに調査します。

**Comment by veigr** [comment]
![port](https://cloud.githubusercontent.com/assets/6935991/9325462/7ab2d77e-45cd-11e5-8a3b-324853c2f520.png)

帰投時のAPI呼び出し順が変更された影響で、艦娘の装備情報と、所持装備の情報がずれてしまっているのが原因でしょう。

現仕様だと

* 艦娘の装備情報は、`port`時に所持装備情報から取得
* 所持装備情報は、`slot_item`データから新たに生成

となっているため、帰投後に更新された装備情報が、艦娘の装備情報に反映されていない形になっています。
以前は`slot_item`→`port`の順だったため問題なかったはずでしたが、いつの間にか変更されていました……

ひとまず原因の報告まで。

**Comment by Grabacr07** [comment]
version 4.1.1 で修正しました

**Comment by nizuru** [comment]
お二方対応ありがとうございます。
現在出先で確認できておりませんが帰宅しだい
再現手順で発生しないかどうか確認させていただきます。

なおGitHubの仕様(?)がわかっていないので恐縮ですが
issueを作成した人間が確認後クローズする形でよいのでしょうか？
(バグ票を起票して修正動作確認後そのバグ票をクローズするのはバグ票を起票した本人といったイメージ)

**Comment by nizuru** [comment]
ver4.1.1で落ちないことを確認いたしました。
ありがとうございます。
念のため二回試しましたが
・母港帰還後に艦隊タブ上でのポップアップの熟練度が改装画面と同じであること
・画面遷移を行わずに装備一覧ボタンを押下してもKanColleViewerプロセスが落ちないこと
(veigrさんの情報を元にこちらの手順も行いました)

いつもKanColleViewerならびにEventMapHpViewer　BattleInfoPlugin　LvChartPlugin にお世話になってます。
本当にありがとうございました。

(こちらのissueは念のため20日にクローズしたいと思います。)

**Comment by nizuru** [comment]
こちらクローズいたします。
ありがとうございました。
