### ISSUE TITLE
[Ver 4.1.3] 起動時にプロキシ設定が反映されない？

### ISSUE THREAD

**Issue by Butter-Knife** [Grabacr07/KanColleViewer#163]
開発お疲れ様です。
4.1.3にて以下のような症状を確認しましたので報告します。

・KanColleViewer起動後「このページは表示できません」のIEエラー画面が表示される。
・Setting→通信設定ではプロキシを使用するよう設定されている。
・一度「プロキシを使わない」をチェックして適用ボタンを押し、リロードボタンを押すと艦これに繋がる。
・この状態で改めて「プロキシサーバーを設定する」をチェックし、適用ボタンを押すと正常にプロキシを通して艦これに繋がる。以後は普通にプレイできる。

という感じです。一度KanColleViewerを終了すると、上記の症状が再現します。
プロキシ設定の読み込みか保存で何か不具合があるのかな、と思いましたが、エラーログは作成されていませんでした。
OSはWindows10 Proです。

**Comment by veigr** [comment]
今のところ私もぐらばくさんも再現出来ていないのですが、具体的な設定や、使用している他のプロキシソフトとその接続設定、より具体的な操作手順(エラーが表示されるタイミング等)などを教えていただけると、調査が進められるかもしれません。

1つ考えられるのは、「プロキシ サーバーを指定する」設定を用いた場合、4.1.3以前はHTTPのみ指定サーバーに接続し、それ以外はIEの設定を流用していましたが、4.1.3以降は全プロトコル(HTTP, HTTPS, FTP)において指定のサーバーに接続されるよう変更された点が影響している可能性です。
もしHTTPSを通せないソフトが上流にいる場合は、初期画面は表示されても「今すぐ出撃!!」ボタン押下後にログイン画面に接続できなくなるといった事はあり得るでしょう。

また他にも4.1.3の変更点として影響がありそうな点は、今までは「今すぐ出撃!!」ボタンがある初期ページの表示は常にIEのプロキシ設定が適用され、KanColleViewer の設定は無視されていましたが、初期ページから KanColleViewer のプロキシ設定が反映されるようにした変更です。
具体的には、起動直後(WebBrowserコントロール初期化時)は about:blank を表示し、KanColleViewer の画面と内部プロキシサーバー(Nekoxy)が立ち上がった後に初期ページに遷移するよう変更しています。
環境によっては何らかの要因によってこの遷移が失敗することはもしかしたらあるのかもしれません。(ちょっと具体的な例は思いつきませんが…)

**Comment by Butter-Knife** [comment]
アドバイスありがとうございます。
同時に使用しているプロキシ対応ツールは 航海日誌 Ver.0.9.3、MyfleetGirls Ver.1.4.3 でした。今までの設定では。KanColleViewerが航海日誌の待ち受けアドレス [localhost:8888]に接続、
さらに航海日誌はMyfleetGirlsの [localhost:8801]に接続。
この二つのローカルプロキシ(用語間違ってたらスミマセン)を通して接続していました。
DMMからログアウトした状態で上記の設定で接続すると、veigrさんの仰るように「今すぐ出撃！」ボタンを押した後エラー画面になりました。画像を添付しておきます。

![2015-08-29 09 21 18](https://cloud.githubusercontent.com/assets/8330494/9559499/7369dd9a-4e2f-11e5-8e7c-574ed929ae11.png)

とりあえずの措置として、インターネットオプションを変更したところ今まで通り繋がるようになりました。
・「自動的に設定を検出する」のチェックをはずす
・「自動構成スクリプトを使用する」にチェック。航海日誌から作成されたproxy.pacを指定
・KanColleViewerで「Internet Explorerのプロキシ設定を使用する」に設定

KanColleViewer自信がプロキシサーバーを使用する設定に戻すと、やはり起動後にエラー画面が表示されるのは変わりませんでした。

>具体的には、起動直後(WebBrowserコントロール初期化時)は about:blank を表示し、KanColleViewer の画面と内部プロキシサーバー(Nekoxy)が立ち上がった後に初期ページに遷移するよう変更しています。
>環境によっては何らかの要因によってこの遷移が失敗することはもしかしたらあるのかもしれません。(ちょっと具体的な例は思いつきませんが…)

この症状が発生している可能性があるかも？
風雲掘りの合間にいろいろ試してみようと思います。

**Comment by iuluvasu** [comment]
開発お疲れ様です。
Windows7Proで航海日誌0.9.3を併用したKanColleViewer4.1.3で同じ症状を確認しました。
発生時の接続設定はButter-Knifeさんとおなじで、4.1.1では発生しませんでした。

発生するタイミングは艦これトップ画面の今すぐ出撃ボタンを押してログイン認証画面に
遷移するタイミングで上記画面が表示されます。
・プロキシサーバを使用しない
・IEのプロキシ設定を使用する
では発生しませんが（ログイン画面に遷移する）IEのプロキシ設定を使用するでは
プレイ可能な状態になるものの、ローカルプロキシは経由せず、DIRECTで接続している
ようです（航海日誌側の情報が更新されないことより判断）。

航海日誌の自動構成スクリプトを使用しており、内容は以下のとおりとなっております。
function FindProxyForURL(url, host) {
  if (/^125\.6\.189\.215/.test(host)) {
     return "PROXY localhost:8888; DIRECT";
  }
  return "DIRECT";
}

以上、ご参考になりましたら幸いです。

**Comment by iuluvasu** [comment]
追記です。
・IEのプロキシ設定を使用する
で、一旦ログインを経由して艦これの開始画面が表示されたあと
・プロキシサーバを指定する
で、ローカルプロキシに切り替えて艦これを開始すると、今まで通り航海日誌経由で使用できるようです。

**Comment by veigr** [comment]
原因はわかりました。
現時点での回避策は提示できますが、KanColleViewerの仕様を今後どうするかはまた考えます。
(このまま行くか、ブラウザのようにもっと細かく設定できるようにするか、「プロキシサーバを指定する」オプションを削除するか……)

### 原因

* 航海日誌はHTTPS通信を利用できないため
(MyfleetGirlsの動作は未確認)
* KanColleViewer 4.1.3 から「プロキシサーバを指定する」で指定したサーバーにHTTPS含む全プロトコルの通信を流すようになったため

KanColleViewerの「プロキシサーバを指定する」の設定は、4.1.3からHTTPS/FTPについても反映されるようになりました。(それ以前はHTTPのみの指定となり、HTTP以外はIEの設定を流用)
そのため、「プロキシサーバを指定する」により指定された上流プロキシがHTTPSを利用できない場合、通信できない問題が発生するようになります。

現在の艦これおよびDMMが利用する通信は、ログイン画面(DMMサーバー)のみHTTPSで、それ以外(艦これサーバー)はHTTP通信です。
そのため、HTTPSを利用できないプロキシを通した場合はログイン画面のみ利用できず、それ以外では問題が発生しない状態になります。

今回の場合は少なくとも航海日誌はHTTPS通信を利用できず、「このページは表示できません」となってしまうのは確認しました。
(MyfleetGirlsについては動作を確認していないため不明です)

IE設定の「自動構成スクリプトを使用する」にてpacファイルを指定した場合に問題が発生しないのは、艦これサーバーへの通信のみ航海日誌を通し、ログイン画面含むそれ以外の通信は航海日誌を通さずサーバーと直接通信するよう構成されているためでしょう。

Fiddler のように HTTPS を通しても問題のないプロキシに関しては、このような問題は発生しません。

### 回避策

以下のいずれか

* KanColleViewer では「Internet Explorer のプロキシ設定を使用する」を指定し、IEの設定では上流に設定したいプロキシツール指定のpacファイルを「自動構成スクリプトを使用する」に設定する
![proxypacsettings](https://cloud.githubusercontent.com/assets/6935991/9561072/5d3dead8-4e71-11e5-860b-c550e8a42cc7.png)
* KanColleViewer では「Internet Explorer のプロキシ設定を使用する」を指定し、IEの設定ではhttpのみ上流プロキシツールを通るよう設定する
![ieproxysettings](https://cloud.githubusercontent.com/assets/6935991/9561030/c6f42c8c-4e6f-11e5-93a5-5f4253aa9a67.png)

なおKanColleViewerは4.1.3以前はIE設定の自動構成が反映されませんでしたが、4.1.3では反映されるよう変更されているため、pacファイルも利用できるようになっています。

### [おまけ] pac ファイルによる自動構成のメリット・デメリット

##### メリット

* 設定が柔軟
* 設定が比較的簡単

##### デメリット

* IE11 以降ローカルのpacファイルの指定が簡単にはできなくなった
* かといってインターネット上のpacファイルは改ざん等を考慮すると危険すぎる
* pac ファイルを作成したプロキシツールの利用では問題なくても、他プロキシツールとの併用や外部プロキシサーバー必須環境などで問題が発生する可能性がある
* WPAD(「設定を自動的に検出する」で設定が検出可能な)環境下では適用されない

**Comment by Butter-Knife** [comment]
原因及び回避策の解説ありがとうございました。

MyfleetGirlsについてもいろいろと設定を試してみましたが、航海日誌同様にhttpsは通らないようです。（データ送信先の[myfleet.moe](https://myfleet.moe)のみにhttps接続するっぽい？）
[MyfleetGirls](https://github.com/ponkotuy/MyFleetGirls)の過去issueも読んでみたのですが、知識が足りずよくわかりませんでした（´・ω・）。
pacファイルについての説明も考慮して、とりあえず2番目のHTTPだけ航海日誌に流す設定を適用し、問題が無いことを確認しました。航海日誌の現バージョンは多段プロキシに対応してますので、そちらでMyfleetGirlsにデータを流してやれば問題ないようです。

**Comment by iuluvasu** [comment]
原因究明ありがとうございました。

こちらも回避策２で正常動作することを確認いたしました。

**Comment by huoyaoyuan** [comment]
I think it's the fault of lookbook, not KanColleViewer. Because when I set proxy route as Browser->lookbook->ShimakazeGo, the HTTPS session cannot be sent to ShimakazeGo as well. So I think there should be some issues in lookbook. 
Lookbook-ex(Nekopanda) 1.9.12 confirmed.

**Comment by c933103** [comment]
@huoyaoyuan you mean logbook? Read veigr's post.

**Comment by veigr** [comment]
4.1.5 以降、プロトコル別に上流プロキシの指定ができるようになりました。
HTTP しか通せないプロキシ型ツールに関しては、この機能を利用して HTTP のみ当該ツールを通すよう設定すれば回避できるのではないかと思います。

**Comment by Butter-Knife** [comment]
>4.1.5 以降、プロトコル別に上流プロキシの指定ができるようになりました。

前回のpost後、航海日誌を常時立ち上げておかないと艦これ以外のサイトも見られないことに気付いて(まあそうなるな(･ω･))、結局proxy.pacを使ってました。
4.1.5でhttpのみ航海日誌を通すように設定したところ問題なく接続できました。
proxy.pacをリモートに置いて使ってたからか、微妙に通信が遅かったのも改善されました。
ホント助かりました。ありがとうございます！
