### ISSUE TITLE
Persistent borders/accent colors.

### ISSUE THREAD

**Issue by AndySun25** [Grabacr07/KanColleViewer#165]
I've run into an issue where the the [window borders persist](https://dl.dropboxusercontent.com/u/88206266/KanColle/border.png) across all virtual desktops despite being only open on 1 in Windows 10. A similar issue where the window border persisted on the desktop despite the window being minimized was also observed on Windows 8.1 (not yet replicated in 10).

I've tested this on 2 PCs using both Win8.1 and 10 thus far and both have exhibited this phenomenon.

**Comment by Grabacr07** [comment]
What is the version of KanColleViewer?

**Comment by AndySun25** [comment]
Yuubari's fork 3.8.1

**Comment by Grabacr07** [comment]
Please discuss in forked repository.
This problem has been improved in the latest version of this repository.
