### ISSUE TITLE
Crash after KB3132372

### ISSUE THREAD

**Issue by Yoctillion** [Grabacr07/KanColleViewer#176]
KB3132372 is a security update of Flash Player.
It seems that after installing this update, program will crash when starting loading flash, and will not leave error log.

**Comment by smdhz** [comment]
It happens with me too, and it leaves this in VS debug mode:
The following error was encountered: TF400813: Resource not available for anonymous access. Client authentication required.

**Comment by liuhx9988** [comment]
Same problem here

**Comment by Federer343** [comment]
I'm having the same problem but I don't have the new Flash update.

**Comment by eD1s0n** [comment]
Uninstalled KB3132372 and KCV stopped crashing, so it is very likely that the update is causing the problem.

**Comment by Katsuga** [comment]
oh thanks a lot, it works perfectly now !

**Comment by cpang6** [comment]
Security and update-wise speaking, it seems like a temporary solution to just uninstall an update. There has to be a more permanent way to fix it.

**Comment by lanhao34** [comment]
I met the same problem, and I install a new win10 in vmware.
It works well before I restart (update).
So I knew there must something wrong with update and I find this issue.

**Comment by Arx105** [comment]
Recently during the combat screen only, I've been getting a LOT of lag. Started happening since the last Kancolle update. Yet when I sign up to DMM. I experience no lag at all. Is this a viewer problem that will be fixed next update?

**Comment by Grabacr07** [comment]
Update has been delivered from Microsoft.
https://support.microsoft.com/ja-jp/kb/3133431
