### ISSUE TITLE
Crash on expedition finishing screen.

### ISSUE THREAD

**Issue by AndySun25** [Grabacr07/KanColleViewer#183]
Using version 4.2.0 of Yuubari's fork KCV crashes randomly on expedition completion screen (where experience and resource gain is shown).
Can't seem to find any consistency in the crashes and no additional info is shown during crash.

**Comment by Grabacr07** [comment]
Discuss in forked repository, please.
In addition, this issue is a problem of Flash Player, so it's not the scope of our work.
