### ISSUE TITLE
[4.2.3]16/04/01のメンテナンス後、情報を取得しない

### ISSUE THREAD

**Issue by slfmoon** [Grabacr07/KanColleViewer#184]
環境: Win10 x64 Pro
症状: 提督業も忙しい！上でログインし、GAME STARTを押しても、ステータスバーが"艦これの起動を待っています"のままで、情報を取得しない。

**Comment by Grabacr07** [comment]
@4492aacc9b0b886dd81ef5e4c5346fb232a5c5f5
