### ISSUE TITLE
自動的にスタートメニューに追加しないでください

### ISSUE THREAD

**Issue by smdhz** [Grabacr07/KanColleViewer#188]
仕事中にボースが見られたやばいです
マジで

**Comment by Grabacr07** [comment]
通知のために必要です (Windows の仕様)。
通知をすべて切れば追加されなくなります。

**Comment by smdhz** [comment]
なるほど、勉強になりました。

**Comment by Yoctillion** [comment]
I think it will be better to set `ShortcutWorkingFolder` property for `Grabacr07.KanColleViewer.Plugins.Toast.request` in built-in plugin `WindowsNotifier`.
