### ISSUE TITLE
最大保有可能 装備アイテム数のずれ

### ISSUE THREAD

**Issue by nagahamago** [Grabacr07/KanColleViewer#189]
ゲーム内の艦隊司令部情報では1220なのに
アプリ側での保有装備が1217になってしまってます
![aabd439270ed3420234f07c9297d74ab](https://cloud.githubusercontent.com/assets/16712231/14840065/74d65e7e-0c6b-11e6-8bb9-ac0255e25868.png)

**Comment by twinkfrag** [comment]
確か保有装備枠いっぱいでランキング報酬が入手できないことを防ぐのために確保されている分で，通常では入手できないためAPIが返している値は1217が正解だったように記憶しています．

**Comment by Grabacr07** [comment]
@twinkfrag さんの仰るとおりで、API で返ってくる値は「この数値以上になると、建造や開発ができなくなる」値、即ち 1217 です。
艦これは表示する際に +3 しているだけで、内部的には 1217 で扱われています。

よって、これは仕様です。

**Comment by nagahamago** [comment]
了解です。ありがとうございました
