### ISSUE TITLE
艦娘一覧で改造完了艦娘に瑞鶴・翔鶴の改二甲が表示されない

### ISSUE THREAD

**Issue by herohiro** [Grabacr07/KanColleViewer#191]
タイトルの通りで、艦娘一覧で改造完了にチェックを入れた際に、瑞鶴改二甲・翔鶴改二甲が表示されません。
(甲じゃない場合に表示されていたかは未確認)
甲の場合でも改造完了に表示されてくれると良いと思います。

**Comment by veigr** [comment]
どう対処すべきかは別として……

とりあえず改二は改二甲に、改二甲は改二に改造可能なため、改造完了として扱われないのが原因となります。
ので改二も改造完了になりませんし、霞でも同様の問題は発生します。

**Comment by herohiro** [comment]
回答ありがとうございます。
不具合かと思っていたので、いずれ対処いただければ幸いです。
