### ISSUE TITLE
一括解体すると所有装備数が更新されない

### ISSUE THREAD

**Issue by chobitsky** [Grabacr07/KanColleViewer#233]
新規追加された機能の時からずっと起きているのですが一応ご報告を。
一括装備解体は反映されるのですが、艦娘の装備をつけたまま一括解体をすると
ウインドウの「保有装備」の数値が更新されないです。

現時点だとリロードするかなにか特別な画面遷移をした場合だけ反映されるみたいです。
こちらのご対応をお願いいたします。

**Comment by Grabacr07** [comment]
fixed by 8b46abf94ef80207ff9e92f9c2106fa25056b979

**Comment by chobitsky** [comment]
ご対応ありがとうございました
