### ISSUE TITLE
cross platform compiling

### ISSUE THREAD

**Issue by ElliotZ** [Grabacr07/KanColleViewer#89]
I noticed that this tool is designed for Windows ONLY.
Considering there may be KanColle players using different systems, will there, by any possibility, be a KanColleViewer for other platforms such as Mac and Linux?

**Comment by amazingfate** [comment]
since Microsoft has taken .NET opensource:http://news.microsoft.com/2014/11/12/microsoft-takes-net-open-source-and-cross-platform-adds-new-development-capabilities-with-visual-studio-2015-net-2015-and-visual-studio-online/
maybe we can have a try, change the browser from IE to firefox or chromium

**Comment by Provissy** [comment]
@amazingfate any

**Comment by Provissy** [comment]
@amazingfate any relation between .net open source and using chrome?

**Comment by amazingfate** [comment]
@Provissy I mean KCV use IE, but on Linux or OS X an opensource browser is better

**Comment by Provissy** [comment]
They don't support WPF
